### ISSUE TITLE
Infos - Sobre o projeto

### ISSUE THREAD

**Issue by glaucia86** [braziljs/community-content#1]
Boa tarde tudo bem?
Queria saber se ainda tá de pé esse projeto. Pois se sim, enviarei o meu form via README.md para vocês! :D

**Comment by jaydson** [comment]
Oi @glaucia86! Está de pé sim, mas ainda em fase de construção e definições.
Mas pode já enviar sim! 🎉

**Comment by glaucia86** [comment]
@jaydson blz. até o final desse mês já envio conteúdo.
